### ISSUE TITLE
Address 

### ISSUE THREAD

**Issue by kostaspanagias** [input-output-hk/cardano-documentation#20] opened 2021-06-19 12:52 UTC
In the "Address" section there is also "Adrestia" definition.

**Comment by olgahryniuk** [comment] 2021-08-11 12:44
Can you please clarify what the issue is? We have glossary definitions, these are correct and both are provided as separate definitions.

**Comment by olgahryniuk** [comment] 2021-08-30 07:20
Closing this issue because of lack of details. Please feel free to open a new one with a detailed explanation of the issue you noticed.
Thank you!

**Closed by olgahryniuk** 2021-08-30 07:20 UTC
